# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
