# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-15 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别')),
                ('birthdate', models.DateField(verbose_name='出生日期')),
                ('height', models.FloatField(verbose_name='身高(cm)')),
                ('weight', models.FloatField(verbose_name='体重(kg)')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='经度')),
                ('tempature', models.FloatField(verbose_name='温度')),
                ('heart_rate', models.PositiveIntegerField(verbose_name='心率')),
                ('oxygen_saturation', models.FloatField(verbose_name='血氧饱和度')),
                ('position_x', models.FloatField(verbose_name='人体姿态x参数')),
                ('position_y', models.FloatField(verbose_name='人体姿态y参数')),
                ('position_z', models.FloatField(verbose_name='人体姿态z参数')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
        ),
    ]
