# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
