# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-26 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_items_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
    ]
