# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='movie.Items'),
        ),
    ]
